### ISSUE TITLE
Does not build with GHC-8.10

### ISSUE THREAD

**Issue by recursion-ninja** [finnsson/template-helper#12]
The Template Haskell API has a breaking change introduced in `ghc-8.10`. The `language-haskell-extract` package needs to be updated for compatibility. When building the following error occurs:

```
Configuring language-haskell-extract-0.2.4...
Preprocessing library for language-haskell-extract-0.2.4..
Building library for language-haskell-extract-0.2.4..
[1 of 1] Compiling Language.Haskell.Extract ( src/Language/Haskell/Extract.hs, dist/build/Language/Haskell/Extract.o, dist/build/Language/Haskell/Extract.dyn_o )

src/Language/Haskell/Extract.hs:28:30: error:
    • Couldn't match expected type ‘Maybe Exp’ with actual type ‘Exp’
    • In the expression: LitE $ StringL n
      In the first argument of ‘TupE’, namely
        ‘[LitE $ StringL n, VarE $ mkName n]’
      In the expression: TupE [LitE $ StringL n, VarE $ mkName n]
   |
28 |      let makePair n = TupE [ LitE $ StringL n , VarE $ mkName n]
   |                              ^^^^^^^^^^^^^^^^

src/Language/Haskell/Extract.hs:28:49: error:
    • Couldn't match expected type ‘Maybe Exp’ with actual type ‘Exp’
    • In the expression: VarE $ mkName n
      In the first argument of ‘TupE’, namely
        ‘[LitE $ StringL n, VarE $ mkName n]’
      In the expression: TupE [LitE $ StringL n, VarE $ mkName n]
   |
28 |      let makePair n = TupE [ LitE $ StringL n , VarE $ mkName n]
   |                                                 ^^^^^^^^^^^^^^^
cabal: Failed to build language-haskell-extract-0.2.4
```

**Comment by RyanGlScott** [comment]
Here is one possible way to patch `language-haskell-extract` to make it compile with `template-haskell-2.16.0.0`, [courtesy of `head.hackage`](https://gitlab.haskell.org/ghc/head.hackage/-/blob/e48738ee1be774507887a90a0d67ad1319456afc/patches/language-haskell-extract-0.2.4.patch):

```diff
diff --git a/src/Language/Haskell/Extract.hs b/src/Language/Haskell/Extract.hs
index 3e8958b..43dfe04 100644
--- a/src/Language/Haskell/Extract.hs
+++ b/src/Language/Haskell/Extract.hs
@@ -1,3 +1,4 @@
+{-# LANGUAGE CPP #-}
 module Language.Haskell.Extract (
   functionExtractor,
   functionExtractorMap,
@@ -25,7 +26,11 @@ extractAllFunctions pattern =
 functionExtractor :: String -> ExpQ
 functionExtractor pattern =
   do functions <- extractAllFunctions pattern
-     let makePair n = TupE [ LitE $ StringL n , VarE $ mkName n]
+     let makePair n = TupE
+#if MIN_VERSION_template_haskell(2,16,0)
+                           $ map Just
+#endif
+                           [ LitE $ StringL n , VarE $ mkName n]
      return $ ListE $ map makePair functions
 
 
```

**Comment by igrep** [comment]
I've created a fork to fix it. https://github.com/igrep/template-helper/commit/5255a3e305c6dfb6762e8a10367e8f528b4801fc.
